In [1]:
import numpy as np

# Step 1: Define dataset
X = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])  # Input features
y = np.array([0, 0, 0, 1])

In [2]:
X

array([[0, 0],
       [0, 1],
       [1, 0],
       [1, 1]])

In [3]:
y

array([0, 0, 0, 1])

In [4]:
# Step 2: Initialize weights and bias
weights = np.random.rand(2)  # Random weights for 2 features
bias = np.random.rand()      # Random bias
learning_rate = 0.1          # Learning rate

In [5]:
weights

array([0.3125252 , 0.39178974])

In [6]:
bias

0.1947827533443186

In [7]:
# Step 3: Train perceptron
for epoch in range(10):  # Train for 10 epochs
    print(f"Epoch {epoch+1}")
    for i in range(len(X)):
        # Forward pass
        z = np.dot(X[i], weights) + bias  # Weighted sum
        y_pred = 1 if z >= 0 else 0       # Step function

        # Calculate error
        error = y[i] - y_pred

        # Update weights and bias
        weights += learning_rate * error * X[i]
        bias += learning_rate * error

        print(f"Input: {X[i]}, Predicted: {y_pred}, Error: {error}")

Epoch 1
Input: [0 0], Predicted: 1, Error: -1
Input: [0 1], Predicted: 1, Error: -1
Input: [1 0], Predicted: 1, Error: -1
Input: [1 1], Predicted: 1, Error: 0
Epoch 2
Input: [0 0], Predicted: 0, Error: 0
Input: [0 1], Predicted: 1, Error: -1
Input: [1 0], Predicted: 1, Error: -1
Input: [1 1], Predicted: 0, Error: 1
Epoch 3
Input: [0 0], Predicted: 0, Error: 0
Input: [0 1], Predicted: 1, Error: -1
Input: [1 0], Predicted: 0, Error: 0
Input: [1 1], Predicted: 1, Error: 0
Epoch 4
Input: [0 0], Predicted: 0, Error: 0
Input: [0 1], Predicted: 0, Error: 0
Input: [1 0], Predicted: 0, Error: 0
Input: [1 1], Predicted: 1, Error: 0
Epoch 5
Input: [0 0], Predicted: 0, Error: 0
Input: [0 1], Predicted: 0, Error: 0
Input: [1 0], Predicted: 0, Error: 0
Input: [1 1], Predicted: 1, Error: 0
Epoch 6
Input: [0 0], Predicted: 0, Error: 0
Input: [0 1], Predicted: 0, Error: 0
Input: [1 0], Predicted: 0, Error: 0
Input: [1 1], Predicted: 1, Error: 0
Epoch 7
Input: [0 0], Predicted: 0, Error: 0
Input: [0 1],