# Initialization methods

## Constant Initialization

In [ ]:
import tensorflow as tf

# Create a tensor filled with the constant value 5
tensor = tf.constant(5, shape=(2, 3))
print("Constant Tensor:\n", tensor)

Constant Tensor:
 tf.Tensor(
[[5 5 5]
 [5 5 5]], shape=(2, 3), dtype=int32)


## Zeros Initialization

In [ ]:
tensor_zeros = tf.zeros([3, 4])  # A 3x4 tensor filled with zeros
print("Zeros Tensor:\n", tensor_zeros)

Zeros Tensor:
 tf.Tensor(
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]], shape=(3, 4), dtype=float32)


## Ones Initialization

In [ ]:
tensor_ones = tf.ones([2, 3])  # A 2x3 tensor filled with ones
print("Ones Tensor:\n", tensor_ones)

Ones Tensor:
 tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]], shape=(2, 3), dtype=float32)


## Random Initialization

In [ ]:
tensor_random_normal = tf.random.normal(shape=(3, 3), mean=0.0, stddev=1.0)
print("Random Normal Tensor:\n", tensor_random_normal)

Random Normal Tensor:
 tf.Tensor(
[[ 0.13887574  0.25227627 -1.764365  ]
 [-0.08540704 -0.18802713 -0.27785048]
 [-0.84171367 -1.0906374  -1.0582969 ]], shape=(3, 3), dtype=float32)


In [ ]:
tensor_random_uniform = tf.random.uniform(shape=(3, 3), minval=0, maxval=1)
print("Random Uniform Tensor:\n", tensor_random_uniform)


Random Uniform Tensor:
 tf.Tensor(
[[0.6475116  0.5125594  0.07972097]
 [0.04187167 0.21993303 0.03118157]
 [0.9155289  0.35433626 0.6551764 ]], shape=(3, 3), dtype=float32)


## Identity Initialization

In [ ]:
tensor_identity = tf.eye(3)  # 3x3 identity matrix
print("Identity Tensor:\n", tensor_identity)

Identity Tensor:
 tf.Tensor(
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]], shape=(3, 3), dtype=float32)


## Custom Initialization (Using a Function)

In [ ]:
def custom_initializer(shape, dtype=None):
    return tf.random.uniform(shape, minval=0, maxval=1)

custom_tensor = tf.Variable(custom_initializer([2, 2]))
print("Custom Initialized Tensor:\n", custom_tensor)

Custom Initialized Tensor:
 <tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[0.8842    , 0.72399926],
       [0.64919794, 0.16025949]], dtype=float32)>


## Predefined Initializers for Neural Networks

In [ ]:
initializer = tf.keras.initializers.GlorotNormal()
tensor_glorot = initializer(shape=(3, 3))
print("Glorot Initialized Tensor:\n", tensor_glorot)

Glorot Initialized Tensor:
 tf.Tensor(
[[ 0.01052565 -0.32128796  0.4194876 ]
 [ 0.9085332  -0.47490087  0.41189346]
 [-0.27114388 -0.42904925 -0.24809851]], shape=(3, 3), dtype=float32)


In [ ]:
initializer = tf.keras.initializers.HeNormal()
tensor_he = initializer(shape=(3, 3))
print("He Initialized Tensor:\n", tensor_he)

He Initialized Tensor:
 tf.Tensor(
[[ 0.12382681 -1.0322969  -0.7480109 ]
 [ 0.4076839  -1.4347541  -0.16560908]
 [ 0.05983094  1.2787173   0.8320883 ]], shape=(3, 3), dtype=float32)


## Tensor Initialization with Shapes Derived from Other Tensors

In [ ]:
tensor_ref = tf.constant([[1, 2], [3, 4]])
same_shape_tensor = tf.ones_like(tensor_ref)
print("Same Shape Tensor:\n", same_shape_tensor)

Same Shape Tensor:
 tf.Tensor(
[[1 1]
 [1 1]], shape=(2, 2), dtype=int32)


# Mathematical operations

In [ ]:
import tensorflow as tf

a = tf.constant([1, 2, 3])
b = tf.constant([4, 5, 6])

# Element-wise addition
result = tf.add(a, b)
print("Addition:\n", result)

Addition:
 tf.Tensor([5 7 9], shape=(3,), dtype=int32)


In [ ]:
result = tf.subtract(a, b)
print("Subtraction:\n", result)

Subtraction:
 tf.Tensor([-3 -3 -3], shape=(3,), dtype=int32)


In [ ]:
result = tf.multiply(a, b)
print("Multiplication:\n", result)

Multiplication:
 tf.Tensor([ 4 10 18], shape=(3,), dtype=int32)


In [ ]:
result = tf.divide(b, a)
print("Division:\n", result)

Division:
 tf.Tensor([4.  2.5 2. ], shape=(3,), dtype=float64)


## Matrix Operations

In [ ]:
matrix1 = tf.constant([[1, 2], [3, 4]])
matrix2 = tf.constant([[5, 6], [7, 8]])

result = tf.matmul(matrix1, matrix2)
print("Matrix Multiplication:\n", result)

Matrix Multiplication:
 tf.Tensor(
[[19 22]
 [43 50]], shape=(2, 2), dtype=int32)


In [ ]:
result = tf.transpose(matrix1)
print("Transpose:\n", result)

Transpose:
 tf.Tensor(
[[1 3]
 [2 4]], shape=(2, 2), dtype=int32)


In [ ]:
result = tf.linalg.det(tf.cast(matrix1, dtype=tf.float32))
print("Determinant:\n", result)

Determinant:
 tf.Tensor(-2.0, shape=(), dtype=float32)


## Aggregation Operations

In [ ]:
tensor = tf.constant([[1, 2, 3], [4, 5, 6]])
result = tf.reduce_sum(tensor)
print("Sum of all elements:\n", result)

Sum of all elements:
 tf.Tensor(21, shape=(), dtype=int32)


In [ ]:
result = tf.reduce_mean(tensor)
print("Mean of all elements:\n", result)

Mean of all elements:
 tf.Tensor(3, shape=(), dtype=int32)


In [ ]:
result_max = tf.reduce_max(tensor)
result_min = tf.reduce_min(tensor)
print("Maximum:\n", result_max)
print("Minimum:\n", result_min)

Maximum:
 tf.Tensor(6, shape=(), dtype=int32)
Minimum:
 tf.Tensor(1, shape=(), dtype=int32)


In [ ]:
result_argmax = tf.argmax(tensor)
result_argmin = tf.argmin(tensor)
print("Index of Maximum:\n", result_argmax)
print("Index of Minimum:\n", result_argmin)

Index of Maximum:
 tf.Tensor([1 1 1], shape=(3,), dtype=int64)
Index of Minimum:
 tf.Tensor([0 0 0], shape=(3,), dtype=int64)


## Element-wise Operations

In [ ]:
tensor = tf.constant([4.0, 9.0, 16.0])
square = tf.square(tensor)
square_root = tf.sqrt(tensor)

print("Square:\n", square)
print("Square Root:\n", square_root)

Square:
 tf.Tensor([ 16.  81. 256.], shape=(3,), dtype=float32)
Square Root:
 tf.Tensor([2. 3. 4.], shape=(3,), dtype=float32)


In [ ]:
exp = tf.exp(tensor)
log = tf.math.log(tensor)

print("Exponential:\n", exp)
print("Logarithm:\n", log)

Exponential:
 tf.Tensor([5.459815e+01 8.103084e+03 8.886111e+06], shape=(3,), dtype=float32)
Logarithm:
 tf.Tensor([1.3862944 2.1972246 2.7725887], shape=(3,), dtype=float32)


## Trigonometric Operations

In [ ]:
angles = tf.constant([0.0, 3.14/2, 3.14])  # Radians

sin = tf.sin(angles)
cos = tf.cos(angles)
tan = tf.tan(angles)

print("Sine:\n", sin)
print("Cosine:\n", cos)
print("Tangent:\n", tan)

Sine:
 tf.Tensor([0.         0.9999997  0.00159255], shape=(3,), dtype=float32)
Cosine:
 tf.Tensor([ 1.0000000e+00  7.9627428e-04 -9.9999875e-01], shape=(3,), dtype=float32)
Tangent:
 tf.Tensor([ 0.0000000e+00  1.2558483e+03 -1.5925501e-03], shape=(3,), dtype=float32)


In [ ]:
arcsin = tf.asin(sin)
arccos = tf.acos(cos)
arctan = tf.atan(tan)

print("Arcsine:\n", arcsin)
print("Arccosine:\n", arccos)
print("Arctangent:\n", arctan)

Arcsine:
 tf.Tensor([0.         1.5700243  0.00159255], shape=(3,), dtype=float32)
Arccosine:
 tf.Tensor([0.        1.57      3.1400104], shape=(3,), dtype=float32)
Arctangent:
 tf.Tensor([ 0.          1.57       -0.00159255], shape=(3,), dtype=float32)


## Logical Operations

In [ ]:
x = tf.constant([1, 2, 3])
y = tf.constant([2, 2, 2])

greater = tf.greater(x, y)
less = tf.less(x, y)
equal = tf.equal(x, y)

print("Greater:\n", greater)
print("Less:\n", less)
print("Equal:\n", equal)

Greater:
 tf.Tensor([False False  True], shape=(3,), dtype=bool)
Less:
 tf.Tensor([ True False False], shape=(3,), dtype=bool)
Equal:
 tf.Tensor([False  True False], shape=(3,), dtype=bool)


In [ ]:
bool1 = tf.constant([True, False, True])
bool2 = tf.constant([False, True, True])

logical_and = tf.logical_and(bool1, bool2)
logical_or = tf.logical_or(bool1, bool2)
logical_not = tf.logical_not(bool1)

print("Logical AND:\n", logical_and)
print("Logical OR:\n", logical_or)
print("Logical NOT:\n", logical_not)

Logical AND:
 tf.Tensor([False False  True], shape=(3,), dtype=bool)
Logical OR:
 tf.Tensor([ True  True  True], shape=(3,), dtype=bool)
Logical NOT:
 tf.Tensor([False  True False], shape=(3,), dtype=bool)


# Indexing in Tensors
Indexing in TensorFlow allows you to access and manipulate specific elements, slices, or sections of a tensor. TensorFlow follows similar indexing rules to NumPy, making it intuitive for Python developers.

In [28]:
import tensorflow as tf

# Define a 1D tensor
tensor = tf.constant([10, 20, 30, 40, 50])

# Access the first element
print("First element:", tensor[0].numpy())

# Access the last element
print("Last element:", tensor[-1].numpy())

First element: 10
Last element: 50


## Slicing Tensors

In [29]:
# Define a 1D tensor
tensor = tf.constant([10, 20, 30, 40, 50])

# Slice elements from index 1 to 3
print("Slice [1:4]:", tensor[1:4].numpy())

# Slice with a step of 2
print("Slice [::2]:", tensor[::2].numpy())

# Slice from index 2 to the end
print("Slice [2:]:", tensor[2:].numpy())

# Slice up to index 3
print("Slice [:3]:", tensor[:3].numpy())

Slice [1:4]: [20 30 40]
Slice [::2]: [10 30 50]
Slice [2:]: [30 40 50]
Slice [:3]: [10 20 30]


## Multi-Dimensional Indexing

In [30]:
# Define a 2D tensor
tensor_2d = tf.constant([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Access an element at row 1, column 2
print("Element at [1, 2]:", tensor_2d[1, 2].numpy())

# Access the entire first row
print("First row:", tensor_2d[0, :].numpy())

# Access the entire second column
print("Second column:", tensor_2d[:, 1].numpy())

Element at [1, 2]: 6
First row: [1 2 3]
Second column: [2 5 8]


In [31]:
# Slice sub-matrix from rows 0-1 and columns 1-2
print("Slice [0:2, 1:3]:\n", tensor_2d[0:2, 1:3].numpy())

Slice [0:2, 1:3]:
 [[2 3]
 [5 6]]


## Ellipsis (...) for Higher Dimensions

In [32]:
# Define a 3D tensor
tensor_3d = tf.constant([
    [[1, 2], [3, 4]],
    [[5, 6], [7, 8]]
])

# Access all elements in the first matrix
print("First matrix:\n", tensor_3d[0, ...].numpy())

# Access all elements in the second row across all matrices
print("Second row across matrices:\n", tensor_3d[:, 1, :].numpy())

First matrix:
 [[1 2]
 [3 4]]
Second row across matrices:
 [[3 4]
 [7 8]]


## Boolean Indexing

In [33]:
# Define a tensor
tensor = tf.constant([10, 20, 30, 40, 50])

# Create a boolean mask
mask = tensor > 30

# Apply the mask
print("Elements greater than 30:", tf.boolean_mask(tensor, mask).numpy())

Elements greater than 30: [40 50]
