In [ ]:
import tensorflow as tf

In [ ]:
zero_d_tensor = tf.constant(5)

In [ ]:
print(zero_d_tensor)

tf.Tensor(5, shape=(), dtype=int32)


In [ ]:
one_d_tensor = tf.constant([0,2,3],dtype=tf.float32)
casted_one_d_tensor = tf.cast(one_d_tensor,dtype=tf.int16)
print(one_d_tensor)
print(casted_one_d_tensor)

tf.Tensor([0. 2. 3.], shape=(3,), dtype=float32)
tf.Tensor([0 2 3], shape=(3,), dtype=int16)


In [ ]:
casted_one_d_tensor = tf.cast(one_d_tensor,dtype=tf.bool)
print(casted_one_d_tensor)

tf.Tensor([False  True  True], shape=(3,), dtype=bool)


In [ ]:
tensor_bool = tf.constant([True,True,False])
print(tensor_bool)

tf.Tensor([ True  True False], shape=(3,), dtype=bool)


In [ ]:
tensor_str = tf.constant(["hello","hi"])
print(tensor_str)

tf.Tensor([b'hello' b'hi'], shape=(2,), dtype=string)


In [ ]:
two_d_tensor = tf.constant([
    [1,2,3],
    [2,3,4],
    [3,4,5],
    [4,5,6]
])
print(two_d_tensor)

tf.Tensor(
[[1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]], shape=(4, 3), dtype=int32)


In [ ]:
two_d_tensor.shape

TensorShape([4, 3])

In [ ]:
three_d_tensor = tf.constant([
    [
        [1,2,3],
        [2,3,4]
    ],
    [
        [3,4,5],
        [4,5,6]
    ],
    [
        [5,6,7],
        [6,7,8]
    ],
    [
        [7,8,9],
        [8,9,10]
    ]
])
print(three_d_tensor)

tf.Tensor(
[[[ 1  2  3]
  [ 2  3  4]]

 [[ 3  4  5]
  [ 4  5  6]]

 [[ 5  6  7]
  [ 6  7  8]]

 [[ 7  8  9]
  [ 8  9 10]]], shape=(4, 2, 3), dtype=int32)


In [ ]:
three_d_tensor.shape

TensorShape([4, 2, 3])

In [ ]:
four_d_tensor = tf.constant([
    [
    [
        [1,2,3],
        [2,3,4]
    ],
    [
        [3,4,5],
        [4,5,6]
    ],
    [
        [5,6,7],
        [6,7,8]
    ],
    [
        [7,8,9],
        [8,9,10]
    ]
],
    [
    [
        [1,2,3],
        [2,3,4]
    ],
    [
        [3,4,5],
        [4,5,6]
    ],
    [
        [5,6,7],
        [6,7,8]
    ],
    [
        [7,8,9],
        [8,9,10]
    ]
],
    [
    [
        [1,2,3],
        [2,3,4]
    ],
    [
        [3,4,5],
        [4,5,6]
    ],
    [
        [5,6,7],
        [6,7,8]
    ],
    [
        [7,8,9],
        [8,9,10]
    ]
]
    ],dtype=tf.float32)
print(four_d_tensor)

tf.Tensor(
[[[[ 1.  2.  3.]
   [ 2.  3.  4.]]

  [[ 3.  4.  5.]
   [ 4.  5.  6.]]

  [[ 5.  6.  7.]
   [ 6.  7.  8.]]

  [[ 7.  8.  9.]
   [ 8.  9. 10.]]]


 [[[ 1.  2.  3.]
   [ 2.  3.  4.]]

  [[ 3.  4.  5.]
   [ 4.  5.  6.]]

  [[ 5.  6.  7.]
   [ 6.  7.  8.]]

  [[ 7.  8.  9.]
   [ 8.  9. 10.]]]


 [[[ 1.  2.  3.]
   [ 2.  3.  4.]]

  [[ 3.  4.  5.]
   [ 4.  5.  6.]]

  [[ 5.  6.  7.]
   [ 6.  7.  8.]]

  [[ 7.  8.  9.]
   [ 8.  9. 10.]]]], shape=(3, 4, 2, 3), dtype=float32)


In [ ]:
import numpy as np

In [ ]:
np_array = np.array([1,2,3])
print(np_array)

[1 2 3]


In [ ]:
converted_tensor = tf.convert_to_tensor(np_array)
print(converted_tensor)

tf.Tensor([1 2 3], shape=(3,), dtype=int64)


In [ ]:
eye_tensor = tf.eye(
    num_rows=3,
    num_columns=None,
    batch_shape=None,
    dtype=tf.dtypes.float32,
    name=None
)
print(eye_tensor)

tf.Tensor(
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]], shape=(3, 3), dtype=float32)


In [ ]:
print(eye_tensor*3)

tf.Tensor(
[[3. 0. 0.]
 [0. 3. 0.]
 [0. 0. 3.]], shape=(3, 3), dtype=float32)


In [ ]:
eye_tensor = tf.eye(
    num_rows=5,
    num_columns=None,
    batch_shape=[2,3],
    dtype=tf.dtypes.float16,
    name=None
)
print(eye_tensor)

tf.Tensor(
[[[[1. 0. 0. 0. 0.]
   [0. 1. 0. 0. 0.]
   [0. 0. 1. 0. 0.]
   [0. 0. 0. 1. 0.]
   [0. 0. 0. 0. 1.]]

  [[1. 0. 0. 0. 0.]
   [0. 1. 0. 0. 0.]
   [0. 0. 1. 0. 0.]
   [0. 0. 0. 1. 0.]
   [0. 0. 0. 0. 1.]]

  [[1. 0. 0. 0. 0.]
   [0. 1. 0. 0. 0.]
   [0. 0. 1. 0. 0.]
   [0. 0. 0. 1. 0.]
   [0. 0. 0. 0. 1.]]]


 [[[1. 0. 0. 0. 0.]
   [0. 1. 0. 0. 0.]
   [0. 0. 1. 0. 0.]
   [0. 0. 0. 1. 0.]
   [0. 0. 0. 0. 1.]]

  [[1. 0. 0. 0. 0.]
   [0. 1. 0. 0. 0.]
   [0. 0. 1. 0. 0.]
   [0. 0. 0. 1. 0.]
   [0. 0. 0. 0. 1.]]

  [[1. 0. 0. 0. 0.]
   [0. 1. 0. 0. 0.]
   [0. 0. 1. 0. 0.]
   [0. 0. 0. 1. 0.]
   [0. 0. 0. 0. 1.]]]], shape=(2, 3, 5, 5), dtype=float16)


In [ ]:
fill_tensor = tf.fill(
    [2,3,4], 8, name=None, layout=None
)
print(fill_tensor)

tf.Tensor(
[[[8 8 8 8]
  [8 8 8 8]
  [8 8 8 8]]

 [[8 8 8 8]
  [8 8 8 8]
  [8 8 8 8]]], shape=(2, 3, 4), dtype=int32)


In [ ]:
one_tensor = tf.ones(
    [2,3,4],
    dtype=tf.dtypes.float32,
    name=None,
    layout=None
)
print(one_tensor)

tf.Tensor(
[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]], shape=(2, 3, 4), dtype=float32)


In [ ]:
ones_like_tensor = tf.ones_like(
    fill_tensor, dtype=None, name=None, layout=None
)
print(ones_like_tensor)

tf.Tensor(
[[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]], shape=(2, 3, 4), dtype=int32)


In [ ]:
rank_tensor = tf.rank(
    three_d_tensor, name=None
)
print(rank_tensor)

tf.Tensor(3, shape=(), dtype=int32)


In [ ]:
tf.size(three_d_tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=24>

In [ ]:
random_tensor = tf.random.normal(
    [3,2],mean=10.0, stddev=0.05, seed=None
)
print(random_tensor)

tf.Tensor(
[[ 9.991317  9.97269 ]
 [ 9.958887  9.970129]
 [10.034279  9.903491]], shape=(3, 2), dtype=float32)


In [ ]:
uniform_tensor = tf.random.uniform(
    [5,],minval=-0, maxval=8, seed=None
)
print(uniform_tensor)

tf.Tensor([6.117071  7.8631077 7.4341764 7.313596  6.4869165], shape=(5,), dtype=float32)


In [ ]:
 uniform_tensor = tf.random.uniform(
    [5,5],minval=-0, maxval=8, seed=None
)
print(uniform_tensor)

tf.Tensor(
[[1.8710909  1.2346659  5.4700365  5.594598   3.3740253 ]
 [5.08348    6.1029377  1.2966175  3.3619184  7.8306227 ]
 [1.4213543  3.7150993  2.5382833  5.175125   0.93380165]
 [0.3466997  6.601673   7.834689   6.6766167  2.1470642 ]
 [5.632144   3.4570189  2.4905567  0.2833948  2.2163057 ]], shape=(5, 5), dtype=float32)


In [ ]:
tf.random.set_seed(5)
print(tf.random.uniform([3,],maxval=5,dtype=tf.int32, seed=10))
print(tf.random.uniform([3,],maxval=5,dtype=tf.int32, seed=10))
print(tf.random.uniform([3,],maxval=5,dtype=tf.int32, seed=10))
print(tf.random.uniform([3,],maxval=5,dtype=tf.int32, seed=10))

tf.Tensor([4 3 1], shape=(3,), dtype=int32)
tf.Tensor([4 3 2], shape=(3,), dtype=int32)
tf.Tensor([1 1 1], shape=(3,), dtype=int32)
tf.Tensor([1 3 3], shape=(3,), dtype=int32)


In [ ]:
tf.random.set_seed(5)
print(tf.random.uniform([3,],maxval=5,dtype=tf.int32, seed=10))
print(tf.random.uniform([3,],maxval=5,dtype=tf.int32, seed=10))
print(tf.random.uniform([3,],maxval=5,dtype=tf.int32, seed=10))
print(tf.random.uniform([3,],maxval=5,dtype=tf.int32, seed=10))

tf.Tensor([4 3 1], shape=(3,), dtype=int32)
tf.Tensor([4 3 2], shape=(3,), dtype=int32)
tf.Tensor([1 1 1], shape=(3,), dtype=int32)
tf.Tensor([1 3 3], shape=(3,), dtype=int32)
