In [1]:
import tensorflow as tf

In [7]:
index_tensor = tf.constant([2,3,5,1,7,0])
print(index_tensor)
print(index_tensor[1])
print(index_tensor[0:3])

tf.Tensor([2 3 5 1 7 0], shape=(6,), dtype=int32)
tf.Tensor(3, shape=(), dtype=int32)
tf.Tensor([2 3 5], shape=(3,), dtype=int32)


In [3]:
tf.range(1,5)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([1, 2, 3, 4], dtype=int32)>

In [10]:
two_d_tensor = tf.constant([
    [1,2,3],
    [2,3,4],
    [3,4,5],
    [4,5,6]
])
print(two_d_tensor[0:4,0:2])

tf.Tensor(
[[1 2]
 [2 3]
 [3 4]
 [4 5]], shape=(4, 2), dtype=int32)


In [11]:
print(two_d_tensor[0:3,:])

tf.Tensor(
[[1 2 3]
 [2 3 4]
 [3 4 5]], shape=(3, 3), dtype=int32)


In [12]:
print(two_d_tensor[...,0:2])

tf.Tensor(
[[1 2]
 [2 3]
 [3 4]
 [4 5]], shape=(4, 2), dtype=int32)


In [13]:
three_d_tensor = tf.constant([
    [
        [1,2,3],
        [2,3,4]
    ],
    [
        [3,4,5],
        [4,5,6]
    ],
    [
        [5,6,7],
        [6,7,8]
    ],
    [
        [7,8,9],
        [8,9,10]
    ]
])
print(three_d_tensor)

tf.Tensor(
[[[ 1  2  3]
  [ 2  3  4]]

 [[ 3  4  5]
  [ 4  5  6]]

 [[ 5  6  7]
  [ 6  7  8]]

 [[ 7  8  9]
  [ 8  9 10]]], shape=(4, 2, 3), dtype=int32)


In [14]:
tf.shape(three_d_tensor)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([4, 2, 3], dtype=int32)>

In [18]:
print(three_d_tensor[0:2,:,0:2])

tf.Tensor(
[[[1 2]
  [2 3]]

 [[3 4]
  [4 5]]], shape=(2, 2, 2), dtype=int32)


In [19]:
print(three_d_tensor[...,:,0:2])

tf.Tensor(
[[[1 2]
  [2 3]]

 [[3 4]
  [4 5]]

 [[5 6]
  [6 7]]

 [[7 8]
  [8 9]]], shape=(4, 2, 2), dtype=int32)
